### PR TITLE
Remove repition of cards

### LINKED ISSUE #326: [bug]: DynamoDB and SQL driver appear twice under "Integrations/All" in Keploy website
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When we navigate to Integrations on the [website](https://keploy.io/), the DynamoDB and SQL driver supported frameworks are displayed twice, as for both golang and java these integrations are available. We can only show them once under `All` such that they are resopectively visible in Golang and Java too.

### Steps to reproduce

1. Go to [website](https://keploy.io/).
2. Navigate to `Integrations/All`.
3. You'll see the following.

Integartions

### Environment

None

### Version

Cloud

### PR DESCRIPTION
**Pull request by hrittikhere**
Fixes https://github.com/keploy/keploy/issues/326

### CODE REVIEW

**Comment by hrittikhere** [comment]
Met @Sonichigo last evening at Foss Kolkata and he introduced me and inspired to start contributing to Keploy 🎉

**Comment by SanskritiHarmukh** [comment]
Hi @hrittikhere , we like your spirit of contributing to Keploy, but the ideal way to do this is by asking to assign you the issue and then you raise a PR fixing the same.

**Comment by hrittikhere** [comment]
Thanks for the pointer. Will keep it in mind :D

**Comment by Ramanjs** [comment]
Hey there, @hrittikhere! I noticed a PR submitted for this issue, but I wanted to offer some feedback on the proposed changes.

After working on this issue myself, I believe an optimal way to solve this issue would be to use the `data-filter` tag on the buttons. I think your current approach deletes the Dynamo DB and SQL integrations completely, so they would not show up in the `Go` section, which would not be optimal. Currently, the items are filtered based on their class, such as `Go`, `Java` and `Node`. To prevent repeated integrations from showing up, we could use the CSS negation pseudo-class `.not()` on the `data-filter` tag of the `All` filter button. I tested this approach by adding a `norepeat` class to the Dynamo DB and SQL Driver integrations in the java section (leaving the go section intact). Using this, we can assign the `*:not(.norepeat)` selector to `data-filter` for the `All` button, and this will filter all the elements without the `norepeat` tag!

One issue still persisted: the filter needed to be applied on the initial website load and not only on transitions from other sections. I also used the `isotope` filter once upon site load to fix this. This gave me the expected effect!

I would be happy to share my code with you and work together to ensure we implement the best solution for this issue. Let me know if you're open to collaborating on this!

**Comment by hrittikhere** [comment]
Hey
That looks like a good approach. How about me closing this and you can move
forward from there?

**Comment by Ramanjs** [comment]
Sure, I'll submit a new PR.

**Comment by hrittikhere** [comment]
Closing in favor of https://github.com/keploy/website/pull/27

**Comment by hrittikhere** [comment]
Closing in favor of https://github.com/keploy/website/pull/27

**Pull request closed without merging**
