### PR TITLE
FEAT : added link in the navbar for keploy blogs

### PR DESCRIPTION
**Pull request by Suman373**
Issue #322
Feature : Introduced a button at Navbar for Keploy blog in hashnode
Assigned by : @SanskritiHarmukh 
Image : 
issue 322

### CODE REVIEW

**Comment by SanskritiHarmukh** [comment]
Hi @Suman373 Can you try making it a nav li instead of a button? Like the docs, programs and community are listed, similar to that. I guess the button looks a bit odd here. I'll change the issue title too. Make changes to this PR itself and sign the DCO after completion.

**Comment by Suman373** [comment]
> Hi @Suman373 Can you try making it a nav li instead of a button? Like the docs, programs and community are listed, similar to that. I guess the button looks a bit odd here. I'll change the issue title too. Make changes to this PR itself and sign the DCO after completion.

Sure, will change it ! Although I have signed the commit before seeing your comment.

**Comment by Suman373** [comment]
@SanskritiHarmukh  Please check if it is alright now ! Thanks !

**Comment by SanskritiHarmukh** [comment]
I have run it locally, works right for me. @nehagup can we take this forward?

**Review by slayerjain — CHANGES_REQUESTED** [review]
@Suman373 there are a lot of ideation/prettifying changes that are making this PR (big) difficult to review. Can you please add only line changes related to this PR?

**Comment by Suman373** [comment]
> @Suman373 there are a lot of ideation/prettifying changes that are making this PR (big) difficult to review. Can you please add only line changes related to this PR?

How do u want me to change all those? @slayerjain

**Comment by slayerjain** [comment]
@Suman373 you can reset to the head of main branch and then add changes only related to this PR and push those.

**Comment by Suman373** [comment]
@slayerjain  I had merging problems in the local, the prev commits are still there. Can I create a new PR with the same issue  ?

**Comment by Suman373** [comment]
@slayerjain Please check if the commit is okay now. Thanks!

**Comment by nehagup** [comment]
@Suman373 can you please tell me which issue is this PR for? 

The blog link you've added is for students blog which can be mentioned either in footer section, Devrel program, api fellowship program website.

**Comment by Suman373** [comment]
@nehagup It's the issue #322 from keploy's repo, which was created and assigned to me by @SanskritiHarmukh . The description was clear, to add a link for students blog.

**Comment by nehagup** [comment]
@Suman373 My apologies, just saw the issue now. It would be great if you please accommodate my feedback as well.

**Comment by Suman373** [comment]
@nehagup It's totally fine. Yes I got your feedback, so where should I add it in footer, and api fellowship website or stop working on this specific issue ?

**Comment by nehagup** [comment]
@Suman373 you can add it to the footer. We're revamping the Devrel cohort and fellowship program API, we'll add it there too later. :)

**Comment by Suman373** [comment]
@nehagup Nice, I'll fix it and create a new PR if that's alright ?!

**Comment by nehagup** [comment]
@Suman373 yes that's ok.

**Pull request closed without merging**
